name: Build and Deploy Angular + CakePHP to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo, pdo_pgsql
          tools: composer:v2

      # Setup Node.js for Angular
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'public/package-lock.json'

      # Install Angular dependencies
      - name: Install Angular dependencies
        run: |
          cd public
          npm ci
          npm dedupe
          npx ng build --configuration production --output-path=dist

      # Install PHP Dependencies
      - name: Install PHP dependencies
        run: |
          if [ -f "composer.json" ]; then
            composer install --prefer-dist --no-progress --no-dev
          fi

      # Package for Deployment (Excluding Unnecessary Files)
      - name: Create deployment package
        run: tar --exclude=public/node_modules --exclude=vendor --exclude=.git --exclude=.github -czf release.tar.gz .

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: php-angular-app
          path: release.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-angular-app

      - name: Extract artifact
        run: tar -xzf release.tar.gz -C $GITHUB_WORKSPACE

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'celescontainerwebapp'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9CA6874FDA9A4C86A3F34CE999A86269 }}
          package: $GITHUB_WORKSPACE  # Deploys the extracted files

      # Ensure PHP dependencies are installed on Azure
      - name: Install Composer Dependencies on Azure
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@your-server-ip 'cd /home/site/wwwroot && composer install --no-dev --optimize-autoloader'
